### ISSUE TITLE
rcpp throws Error: not compatible with requested type error.

### ISSUE THREAD

**Issue by lmkirvan** [bstewart/stm#13]
I've been using the STM package successfully with a number of different text corpus (does corpus have a plural?)

I recently started using it a new set of document and I'm encountering an error that I can't seem to debug. This corpus is slightly larger than what I've done in the past (around 21,000 documents and about 4,900 terms.) Other than that it is a different sub-sample from the same data source that I've successfully used in the past. 

I've pulled down some data from sql with the documents and data in a single dataframe and I've followed the standard steps from the vignette to prepare the documents (which I've successfully done in the past with a number of different data sets) 

When i attempt to use stm()  I get the same error message each time:

`Error: not compatible with requested type`

The error is slightly different depending on the init.type that I use.

With spectral I get the following message:

```
Beginning Initialization.
	 Calculating the gram matrix...
	 Finding anchor words...
 	....................
	 Recovering initialization...
 	.................................................
Initialization complete.
Error: not compatible with requested type
```

for both Random and LDA initialization I get the same error message but directlyafter the message:

`Beginning Initialization.`

I'm pretty sure that this is a scoping problem with the C++ code. but I can't figure it out. 

Let me know if you have questions  or if I can do more to clarify. 

Thanks,

Lewis

**Comment by bstewart** [comment]
Very interesting.  Thanks for bringing this to my attention.  At a bare minimum we will get it set up so this throws a clearer error.

Did you run the documents through prepDocuments?  My guess is that there is something idiosyncratic here like a word which never appears or a document with no words in it.  I'd take a look at the first few documents and see if anything strikes you as obviously wrong and run through prepDocuments if you haven't already.

If not, run sessionInfo() and check that you have the most recent version of the code.  If at that point the problem is still unclear perhaps you could post or email me a small replication file.  Nothing obvious pops to mind so I probably just need to be able to replicate it.

Also the plural of corpus is corpora!

**Comment by lmkirvan** [comment]
I did use prepDocuments which is why the error was especially confusing. I
also removed any really short or null documents before running through
prepDocuments. I'll try to create a minimal version for you, but it might
be a little difficult. I'm using data that isn't public (I work for a
federal agency and I'm using consumer complaint data). Fortunately we do
realease some of our complaint data publicly so if I can't figure out
what's happening I'll try to create a reproducible example using the public
data.

On Tuesday, June 7, 2016, Brandon Stewart <notifications@github.com> wrote:

> Very interesting. Thanks for bringing this to my attention. At a bare
> minimum we will get it set up so this throws a clearer error.
>
> Did you run the documents through prepDocuments? My guess is that there is
> something idiosyncratic here like a word which never appears or a document
> with no words in it. I'd take a look at the first few documents and see if
> anything strikes you as obviously wrong and run through prepDocuments if
> you haven't already.
>
> If not, run sessionInfo() and check that you have the most recent version
> of the code. If at that point the problem is still unclear perhaps you
> could post or email me a small replication file. Nothing obvious pops to
> mind so I probably just need to be able to replicate it.
>
> Also the plural of corpus is corpora!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bstewart/stm/issues/13#issuecomment-224444052>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFMRVcXAsMuMALppDc4P8KUwpM_KwO8sks5qJf3IgaJpZM4IwXMs>
> .
>


-- 
Sent in motion, please excuse brevity/typos

**Comment by bstewart** [comment]
Feel free to email me (bms4@princeton.edu) instead of posting here.  Also one option is to send me the documents object and a fake vocab vector (something like 1:length(vocab)).  That way the documents can't be read.  

I've tried a few different things to recreate the error (just guessing at causes) and really can't come up with anything so I probably will need the documents to work out what is going on.

**Comment by bstewart** [comment]
Did this ever get resolved?  Please feel free to reach out if not.

**Comment by bstewart** [comment]
Another user had this problem and it came from having missing values in the content covariate.  I'm adding error checking but wanted to post a note here in case that helped anyone.
