### ISSUE TITLE
inconsistent output for identical settings

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#133]
Hi Brandon,

I used STM in class today and some students noticed that the output of their topic models was not exactly identical to mine.
I don't think software versions are the reason, as I double checked and verified that the versions for stm  (1.3) and quanteda (0.99) were identical across the machines.

This is the code we used:

```
library(tidyverse)
library(quanteda)
library(stm)


survey <- stm::gadarian # survey datensatz
dfm_survey <- corpus(survey, text_field = 'open.ended.response') %>% 
        dfm(stem = TRUE, remove = stopwords('english'),
            remove_punct = TRUE) %>% 
        dfm_trim(min_count = 2)

dim(dfm_survey) # document feature matrix
[1] 341 482

out <- convert(dfm_survey, to = 'stm') # format fuer stm package

survey_stm <- stm(documents = out$documents, # numerische feature counts
      vocab = out$vocab, # features als strings
      data = out$meta, # datensatz fuer kontextvariablen
      K = 3,  # anzahl der topics
      prevalence = ~ treatment + pid_rep, # prevalence formel
      verbose = FALSE) 

labelTopics(survey_stm, topics = 1:3, n = 15)

Topic 1 Top Words:
 	 Highest Prob: think, tax, us, work, pay, take, worri, learn, welfar, live, go, way, mexico, becom, school 
...
```
An image from the students with the exact same document matrix (no. documents, features) and the same model specification returns similar but not identical words for the topic:
````
Topic 1 Top Words:
Highest Prob: think, get, tax, us, work, pay, need, worri, learn, mani, welfar, languag, way, speak, school
...
````
As of version 1.3, the default initialization is set to spectral, so this should also not be a problem. Another idea I had was that word probabilities might be identical , but this is also not the case:
````
term_topic_probs <- survey_stm$beta$logbeta[[1]] %>% exp() %>% 
  t() %>% round(3) %>% as_tibble() %>% 
  set_names(paste0('Topic', 1:ncol(survey_stm$theta))) %>% 
  mutate(word = out$vocab)
term_topic_probs %>% 
  arrange(desc(Topic1)) %>% select(Topic1, word) %>% head(15)

# A tibble: 15 x 2
   Topic1 word  
    <dbl> <chr> 
 1 0.0520 think 
 2 0.0390 tax   
 3 0.0380 us    
 4 0.0350 pay   
 5 0.0350 work  
 6 0.0340 take  
 7 0.0270 worri 
 8 0.0250 learn 
 9 0.0240 welfar
10 0.0230 live  
11 0.0210 go    
12 0.0190 way   
13 0.0170 becom 
14 0.0170 mexico
15 0.0160 can   
````

Do you have any idea what's going on here?

**Comment by nkorf** [comment]
Just in case, can you try to see if you can get the same results by adding the set.seed() in your code? e.g., set.seed(10) and then execute the code again on different machines?

**Comment by methodds** [comment]
I could try this next week as I would need access to one of the other machines again. But shouldn't the seed be irrelevant with spectral initialization?

**Comment by bstewart** [comment]
Hi guys- thanks for asking.  I sort of do and sort of don't know what's happening here.  

The problem is that despite the fact the spectral initialization is just linear algebra- numerical precision differences between machines can actually cause differences between computers.  So I've noticed this happen most often with Windows 32 bit computers but it seems like it is possible to see a difference in some Windows 64 bit machines as well.  It is this latter part that is so confusing. Regardless, this problem won't go away by setting the seed.

You can get around this problem by using the option `control=list(recoverEG=FALSE)` which uses an alternate approach for handling the recovery step in the Spectral initialization which for whatever reason does not seem to have any differences across machines (I think because it drops down into C to do the calculations).  

I've considered changing the default Spectral initialization to being this other one, but I get very nervous about making changes to default behavior.  Unfortunately I have yet to find a way to force one of the 32 bit machine versions to produce the same result as the 64 bit machine versions other than to start with a preexisting initializations.

**Comment by methodds** [comment]
Thanks Brandon for responding too fast. Does the approach you suggest with using `control=list(recoverEG=FALSE)` result in any disadvantages?

Because from first inspections of running the model from above with this option, the output is different and also somewhat odd: Many high probability terms are listed for several topics:

```
plot.STM(survey_stm, topics = 1:3, n = 15, type = 'labels')
```

![image](https://user-images.githubusercontent.com/7460499/34955301-15886f22-fa24-11e7-831d-01af00ec33c6.png)

**Comment by bstewart** [comment]
So this alternative is a strange one in that ostensibly it should work better than it does.  

Let me see if I can try to explain.  The spectral initialization works by calculating a V by V matrix whose rows are for word v in the vocabulary, the probability of seeing each other words in the vocabulary given that we have seen word v in the document.  In the first step, we find one anchor word per topic(mathematically: the rows of the matrix that are the vertices of the convex hull in which all other rows lie, conceptually: words that have positive probability under only one topic). In the recovery step, we find the convex combination of the anchor word rows to reconstruct each other row in the matrix under some loss (in our setting the L2 loss).  These weights can be turned into an estimate of Beta.

The issue here arises from different ways to do the recovery step.  In the original algorithm they use an exponentiated gradient (EG) descent method which in practice does not seem to find the best solution (it stops early).  We can replace this step with a downhill simplex algorithm that solves the problem essentially exactly.  That's great- but it turns out this often does not perform better in the final model. 

The problem is that we don't care about solving the initialization problem correctly- we care about getting the best solution to the final topic model (these two would line up in a world of infinite data and the DGP holding exactly, but neither are anywhere near true in practice).  An extreme solution might fit the data well but can get us stuck in a way that isn't super useful.  The downhill simplex approach solves the initialization problem really well- but it doesn't seem to provide great solution as long as wide a range of datasets as the exponentiated gradient descent method- and I don't entirely know why.  

I've been working on some other initialization strategies- but the key is clearly finding something that works really well on a huge array of datasets while also being perfectly reproducible across machines.  It took me a long time to find out that the original spectral algorithm wasn't perfectly reproducible- so it has been a continuing search.

I realize that isn't as clearcut as you are probably hoping- but sadly this is an area that is really complicated.  If it helps there are plenty of places the downhill simplex method seems to work really well- but the gadarian dataset (I think because it is short) really isn't one of them.

**Comment by methodds** [comment]
Thanks again Brandon for your explanation, it is very useful for grasping the complexity of this issue. I have to say that to this day I  fitted maaaaaany STM models and never experienced these inconsistencies across my windows and my linux machines, although I always worked with larger datasets.

In the end, there is still absolutely no reason to discard either versions of spectral initialization and go back to LDA initialization right? 

I'd still love to know whether you would in general recommend to rather use the downhill simplex method instead of the default, or would consider other factors, like corpus size, for this decision. For the remaining lectures I will probably stick to the default initialization in order to not overload students with more complicated decisions.

**Comment by bstewart** [comment]
To your first point- this is also how it took me so long to find.  It seems to be the minority of machines.

"Absolutely no reason" is strong language.  No initialization method is absolutely defensible across all possible datasets (a corollary of a more general point that Justin Grimmer and I make about text models in general in [Text as Data](https://doi.org/10.1093/pan/mps028).  So it could always be that LDA initialization just performs better for your data.  Honestly I continue to be surprised that spectral performs well on small datasets since it relies really heavily on asymptotics.  But in a general sense- I think the strongest reason to stick to the LDA initialization is that you can set the seed and have stability across platforms.  I don't think that's going to be enough for most people though.

For now- the standard spectral method is still the first thing I try when I hit a new dataset.  I'm hoping that extensive testing/work will come up with an even better and more robust solution- but I haven't found it yet.

**Comment by bstewart** [comment]
Updated documentation to reflect this information.
