### ISSUE TITLE
termination before convergence

### ISSUE THREAD

**Issue by AnnikaMagnus** [bstewart/stm#177]
I am using STM for open-ended questions in a survey data.
When I try to report the results with a different number of topics, I realize that R terminates before converging for some models. Even when I increase max.emit to 200 from 100, the model does not converge. May I ask you possible reasons for it? and what are possible ways to overcome it?

**Comment by bstewart** [comment]
Sometimes models can take a really long time to converge, but in general they are taking smaller and smaller steps each time.  Often the changes in the very high numbers of iterations are extremely minor.  You can restart a model which has not yet converged though so that's always an option (there is example code in stm's help file).  There isn't really a generic answer for this though.

**Comment by mdomingo14** [comment]
Hi there! 

Unfortunately, I am having the same issue on my macOS Monterey version. How can I overcome this issue? Thank you in advance!

"Completed E-Step (17 seconds). 
Completed M-Step. 
Model Terminated Before Convergence Reached"

**Comment by mdomingo14** [comment]
I also noticed it only gives me this error code when I include prevalence as in the example below:

poliblogSelect <- selectModel(out$documents, out$vocab, K=20, prevalence=~rating+s(day),
                              max.em.its=75, data=meta, runs=20, seed=8458159)

**Comment by luna-diaz** [comment]
You can take out the max.em.its, which stops the iterations once they reach 75. If you write a larger number you allow for more iterations, and if you remove it completely it usually runs until it converges. Be warned, however-- this step can take a LONG time if you do not set up a maximum number of iterations.
