### ISSUE TITLE
findThoughts creates an error

### ISSUE THREAD

**Issue by kevinbsc** [bstewart/stm#18]
thoughts1<-findThoughts(poliblogPrevFit, texts=shortdoc,n=2, topics=1)
plotQuote(thoughts1, width=40, main="Topic 1")

I am getting the following error and output.

Error in findThoughts(poliblogPrevFit, texts = shortdoc, n = 2, topics = 1): object 'shortdoc' not found

![image](https://cloud.githubusercontent.com/assets/3991133/16360276/09910394-3b1e-11e6-898b-29771a59c6f0.png)

Thanks!

**Comment by bstewart** [comment]
See footnote 17 of the vignette.  It is an object in the workspace containing the first few words of each document.  You would replace this with whatever character vector of texts you want to use.

Thus the following should work fine:
```
load(url("http://goo.gl/VPdxlS"))
thoughts1<-findThoughts(poliblogPrevFit, texts=shortdoc,n=2, topics=1)
plot(thoughts1, width=50, main="Topic 1")
```

Something does appear to be a little strange with using plotQuote instead of just plot() which looks like a problem with argument passing.  I'll look into it.

**Comment by bstewart** [comment]
Oh and I remember now.  `plotQuote()` takes the documents as its text argument.  In this context that means you need to do either:

```
plot(thoughts1)
```

or 

```
plotQuote(thoughts1$docs[[1]])
```

because they take slightly different arguments.  This allows for plotQuote() to be effectively used for any texts without using findThoughts() in the first place.

**Comment by kevinbsc** [comment]
Thanks for your prompt response. I am a little confused about the way "findThoughts" is used.

Your suggestion works:

load(url("http://goo.gl/VPdxlS"))
thoughts1<-findThoughts(poliblogPrevFit, texts=shortdoc,n=2, topics=1)
plot(thoughts1, width=50, main="Topic 1")

This returns the expected output. 

However, I would like to know how I am supposed to use findThoughts with my own data and model. 

For example, below is the way I create a model.

#creating a model
mydataPrevFit <- stm(out$documents, out$vocab, K = 20, prevalence =~ restype + s(date), max.em.its = 75, data = out$meta, init.type = "Spectral")

#Is the below script correct?
thoughts1<-findThoughts(mydataPrevFit, n=2, topics=1)
plot(thoughts1, width=50, main="Topic 1")

This returns the following error:
`Error in strsplit(out[[j]], "\n")[[1]] : subscript out of bounds`

Thanks again for your help!

**Comment by kevinbsc** [comment]
I tried the following as well:

`thoughts1=findThoughts(poliblogPrevFit, texts=out$documents, topics=2)`
`plot(thoughts1)`

But, I am getting integer values, instead of texts. I am doing something wrong here. Can you guide me on this? Thanks!

![image](https://cloud.githubusercontent.com/assets/3991133/16420674/dc3db5f8-3d17-11e6-949b-4bc1f38ec486.png)

**Comment by bstewart** [comment]
You need to pass it the texts rather than the documents object.  Look at the shortdoc object, it is a character vector.  You need to pass it something like that.  A vector where each entry is the actual text for that document.

**Comment by kevinbsc** [comment]
Thanks for your answer. So, I think the code below seems working in my case.

`thoughts1=findThoughts(poliblogPrevFit, texts=data$documents, topics=2, n=3)
plot(thoughts1)`

![image](https://cloud.githubusercontent.com/assets/3991133/16421963/4cb98434-3d1c-11e6-9e64-22b6dbdc4d3b.png)

I have two questions.

1. My understanding is that data$documents stores the original content (e.g., news articles, reviews). I use prepDocuments. In my case the lower.thresh (= 20) removes some documents from the original content. So, is it still okay to do "texts =data$documents" since the filtered data are stored in docs <- out$documents, vocab <- out$vocab,  and meta <-out$meta.

2. The above plot shows three "complete" documents. How can I show only the first 10 words or so from each document?

**Comment by bstewart** [comment]
1.  data$documents stores the term-document matrix not the original texts.  You can look at objects using str() if you want to see what they look like.

2. You can limit the maximum number of characters using the maxwidth option in plotQuote.  Otherwise you can always shorten the documents yourself before plotting them.

**Comment by kevinbsc** [comment]
Thanks for your answers!

**Comment by sampritim** [comment]
Hi!
I am trying to do something similar with my data set.
This is my STM model
 CEFit1 <- stm(documents=out$documents, vocab=out$vocab, K=5, prevalence=NULL, max.em.its=75, data=out$meta, init.type="Spectral")
thoughts1 <- findThoughts(CEFit1, texts=data$documents, n=2, topics=1)
But then I get an error message:
Error in findThoughts(CEFit1, texts = data$documents, n = 2, topics = 1) : 
  Number of provided texts and number of documents modeled do not match

How do i get this to work?
