### ISSUE TITLE
[Question] in the implementation of function hpbcpp

### ISSUE THREAD

**Issue by ping-at-git** [bstewart/stm#251]
In STMCfuncs.cpp, function hpbcpp, line 128, the following:

`EB.each_row() %= arma::trans(sqrt(doc_cts))/sum(EB,0);`

If i'm not mistaken, the above implementation is modifying the EB matrix in place, which also means `sum(EB,0)` should have a different value for each iteration. So my question is: is this the intended behavior? or was the intention to have the denominator as the constant version of the column sum of EB without any modification?

**Comment by bstewart** [comment]
I've checked this implementation against several R implementations (as I know R much better than C++) so I'd be really surprised if there is an error here.  These other implementations were slower but much clearer because I didn't have to worry as much about speed.

When you say `sum(EB,0)` should have a different value 'for each iteration' you mean each row right?  I *think* what is happening is it is precomputing the entire right hand side (for both speed and accuracy reasons) and then doing the element-wise multiplication.  That said, I see what you mean and the documentation in armadillo isn't super clear on this point.  Have you run tests suggesting this is wrong or just having a look?
