### ISSUE TITLE
Make package dependencies clearer

### ISSUE THREAD

**Issue by crew102** [bstewart/stm#28]
Hi again -

I'd like to make three changes in my next PR:
1. I think stm should be clearer about the packages it relies on. One of the core functions in the stm workflow, `textProcessor`, uses the tm package a ton for manipulating text, but stm doesn't import this package. It would be easier to just import tm. What do you think? I understand wanting to reduce dependencies, but for such a critical function, I think we should just import it.
2. I'd also like to do away with importing the functions in grDevices, graphics, stats. Can't we just use the `::` function to access these functions?
3. Can we use devtools/Roxygen from now on to create the NAMESPACE and .RD files? I don't like having to hunt down the documentation each time I make a change to a function and need to change its doc. I'm willing to move all of your existing documentation over to Roxygen tags.

Chris

**Comment by bstewart** [comment]
Chris,

First thanks so much for all of this.  Some replies:

Re 1) `tm` has historically had some install problems with certain systems and versions of R.  That's primarily why I was reluctant to import it in particular.  I don't think of `textProcessor` as core functionality because a user can always do their own pre-processing or use `quanteda` etc.  I am thus nervous to introduce limitations to some people's use.

Re 2) This is a great idea.

Re 3) That would be amazing.  I've used Roxygen in some of my more recent developments and its been fantastic- I just haven't had the time to port it over.  If you are willing to do that, I would be hugely grateful.

**Comment by crew102** [comment]
OK assign numbers 2 and 3 to me and I'll get to them sometime this week.

**Comment by bstewart** [comment]
Thanks again for all the amazing work here.  The version in the development branch now is fully compliant with roxygen.  I really appreciate your help on this- it was a big part of me actually getting around and working on it.
