### ISSUE TITLE
textProcessor should remove punctuation before doing anything else

### ISSUE THREAD

**Issue by crew102** [bstewart/stm#29]
I first came across this issue when trying to pass a custom stop word list to `textProcessor`. I was still ending up with some of my stop words appearing in the final output because they were abutting punctuation (e.g., including `customstopwords = "hi"` didn't remove "hi."). This behavior is well-documented in  `textProcessor` but I still think it is not ideal. 

I would like to reorder the functions in `textProcessor` so that punctuation is removed first, then stop words are removed, then stemming is completed. It think this will provide results that are more in line with what the user expects.

I'll issue a PR with these changes (including changes to documentation) if you're amendable to the change.

Chris

**Comment by bstewart** [comment]
Interesting.  The rationale for this was to deal with things like "can't"  The slightly longer but better fix would be to remove punctuation in stages.  Essentially removing everything except apostrophes, then doing stopwords, then remove apostrophes.  This retains user control of the stopword list (so if someone passes a new list it will work as expected).  You are welcome to make that change if you feel comfortable, otherwise I can do it on the next pass.  Thanks for flagging this though- extremely helpful.

**Comment by crew102** [comment]
Yeah, you're right about approstrophes - I didn't think of that. I tried creating a similar function to `textProcessor ` awhile back and I remeber it was tough to get the order right. 

I'll issue a PR sometime this week with the suggestion you made - i.e., wait to remove apostrophes until stopwords have been assessed. 

If you're up for it, I'll also add n-gram functionality (though I won't import anything - I'll do something similar to what you have done for stem words, where SnowballC is checked for on the fly). It can be tricky to get the ordering correct with n-grams too, but I think the solution I came to in my own function seemed to work ok.

**Comment by bstewart** [comment]
Chris I decided you were totally right here.  I moved the punctuation ordering around (still in development branch right now).  You are more than welcome to issue a pull request on this (might be worth waiting until its in the master branch which should be a couple of days).  I do think I am going to try shifting most of the focus on preprocessing over to quanteda.
