### ISSUE TITLE
Multicore benefits?

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#36]
Hi, 

I'm aware that computation-intensive parts of ```STM``` are written in ``c++``. But does ``STM`` in general benefit from multicore setups? As an example, would switching to [MRO](https://mran.microsoft.com/open/) result in a substantial performance increase?

**Comment by bstewart** [comment]
Thanks for asking and so sorry its been so long.  I've had mixed luck with MRO- some things get faster and some get slower.  Its been a while since I benchmarked STM.  

I did not do anything explicitly to maximize multicore setups (most of the stuff seemed very platform dependent which is hard to test).  The computation-intensive parts are down in RCPP armadillo so if Armadillo supports it, I think stm does by default.
