### ISSUE TITLE
Add function to create comparable vocab

### ISSUE THREAD

**Issue by bstewart** [bstewart/stm#40]
When doing the heldout likelihood fitting, you need to have the document numbered in the same way as the original STM model (same vocab, same numbers corresponding to each word).  Need a function that can convert another document set in STM format over to the vocab of the first (i.e. drop extra words and renumber).

@kbenoit Do you have any code for doing this in quanteda that I could include in the help file for users?  The use case would basically be I create a quanteda dfm and now i have some new documents and want what their rows in the original dfm would have been.  No worries if you guys don't do this sort of thing, just thought I'd check.

**Comment by kbenoit** [comment]
Easy to construct for a dfm, trickier when you take it apart as multi-component lists. If I could be so bold, my suggestion to make this easier and to make the infrastructure for getting to estimation of your model easier would be to move your suggested workflow to a dfm rather than your current input object. A dfm has everything you need except the structure variables, but

a) using a dfm is still far more integrated than the multi-component list approach, since there is only the one additional item not included (the covariates) and  
b) to solve even a), we could accelerate our plans to keep the covariates in downstream objects like `tokens` and `dfm` structures. This would mean from a corpus that has covariates for each document, you these would be invisibly attached to a dfm, meaning in the single object, they could be passed to functions such as `textmodel_*` or your `stm` that needed them.

This could be implemented in your code easily by inserting the conversion functions from **quanteda** so you don't have to change how your functions work, just alter the new input to match the old input. Eventually, for efficiency, you would change the input to take the counts and vocabulary from a dfm directly.

With the new and super-fast feature selection tools in **quanteda**, including soon part of speech selection, this would be a major benefit for **stm** users imho.

**Comment by bstewart** [comment]
This is fantastic.  Thanks Ken!

So I hesitate to completely switch because of memory management.  To avoid having to internally create a new copy of the object we would have to rewrite all the guts of the stm package.  

That said- let me give it some serious thought.  I think probably not for the very next release- but longer term I think you are right.

**Comment by kbenoit** [comment]
There would not be any memory management issues, since you can take what you need directly from a dfm and possibly separate - or if we build them in to a dfm - included meta variables. I could write a method into **quanteda** for this, but it would require that `stm()` be written as a generic with the existing function being assigned to `stm.default()`. I could do this in a PR for you, and program the dfm functionality into **quanteda**. You would have the option of course of migrating it to **stm**.
