### ISSUE TITLE
Question: Best use of stm for 1d-scaling

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#43]
Hi Brandon,

as stated in the description of ``STM`` fitting models for only two topics corresponds to a unidimensional scaling. I'd like to ask you about your opinion whether this is reasonable and might even be a better solution than alternative scaling methods.
Say there is a corpus of legislative debates, where document information like speaker_id, speaker_party, debate_id and debate_date are available. Wouldn't STM then be superior than simply using something like wordfish? As we can incorporate more information in the model (e.g. all covariates mentioned above), this should give us better estimates right?
I played around with this a little bit and noticed some things that raised questions:
- As expected ``topicCorr`` reveals that the topics are perfectly correlated. Shouldn't then the ``sigma.prior`` be adjusted and if so, what would be a reasonable value?
- The metric of highest probable words becomes kind of useless, as it basically only captures stop words for both topics. In contrast, the FREX metric is very useful: For a corpus of German legislative debates,  topic 1 frex terms show terms related to economy and topic 2 related to social rights and warfare, which I interpret as a sign that an important dimension was identified by the model.
- Whenever factor variables with a lot of factors (speaker_id, debate_id) are included in the formula for ``estimateEffect`` it raises the warning for a non-singular matrix. How problematic is this for proper estimates? Obviously such factors are crucial for determining speaker positions.
- For this special case, should ``estimateEffect`` parameters like ``nsims`` be adjusted?

Thanks for your help :)
Carsten

**Comment by bstewart** [comment]
Carsten,

Thanks for the questions.  Some replies:

> As expected topicCorr reveals that the topics are perfectly correlated. Shouldn't then the sigma.prior be adjusted and if so, what would be a reasonable value?

No need to adjust.  The underlying modeling is done with a K-1 dimensional multivariate normal.  In this case it just reduces to a univariate normal so "sigma" just works out to be a scalar.

> The metric of highest probable words becomes kind of useless, as it basically only captures stop words for both topics. In contrast, the FREX metric is very useful

Right- I could see lift being useful here too.  I think your interpretation is correct.  FREX is very much what you would want here though.

> Whenever factor variables with a lot of factors (speaker_id, debate_id) are included in the formula for estimateEffect it raises the warning for a non-singular matrix. How problematic is this for proper estimates?
 
It sort of depends.  It adds a very crude ridge penalty to get the estimation running.  If you are okay being a bit Bayesian and your specification makes sense, then you can think about this as similar to having a normal prior.

>For this special case, should estimateEffect parameters like nsims be adjusted?
I don't think so?  Although it starts getting to the point where you might want to think about actually doing the estimation in a different properly Bayesian setting.

Overall, I'm not sure I would expect stm to be superior to wordfish and company here.  I mean I guess its an empirical question and I'll be curious about your experience, but its a very strange data generating process for a scaling model.  I haven't carefully thought through the implications though.  So I guess its an open question.  

I think my biggest concern is with estimateEffect.  estimateEffect operates in the space of the normalized topic proportions (theta) because that is typically the quantity of interest.  In this case though that isn't really true, right?  Our interest is really more in the single underlying dimension.  So it feels like maybe inference should be being done there.  Maybe it doesn't matter, but the choice just seems odd I think.

Long-run I think I would see stm as a stopgap here.  An interesting project would be to do a proper covariate-based scaling model with a similar set of features etc.  This is conceptually straightforward but a decent amount of programming!

**Comment by methodds** [comment]
Thank you for the detailed comments. I guess I hoped that ``STM`` is just a mighty unbeatable swiss army knife ;-)

**Comment by bstewart** [comment]
Would that it were!
