### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by WallyTWalrus** [bstewart/stm#57]
I have a quick question about reproducibility.  What precautions can I take (if any) to make sure that the same exact corpus results in the exact same stm fit from run-to-run (including different machines)?

And, also, while you're at it.  Can I possibly re-fit a subset of the original corpus using the fitNewDocuments function and retrieve the same topic model scores?

Thanks for reading!

**Comment by bstewart** [comment]
You can ensure reproducibility in one of three ways.  
(1) Use the spectral initialization and ensure that you are always using a 64-bit version of R.
(2) Use the default initialization and use set.seed() beforehand
(3) Use the default initialization and use the seed argument in stm to pass it the seed that was produced on a previous run.

You can re-fit a subset of the original corpus using fitNewDocuments and get the same results if you use the "Covariate" priors which match your original model fit and the original model converged.

**Comment by OO00OO00** [comment]
On the same issue, I'm seeing a small portion of documents with materially large differences in theta values, when comparing a fitted topic model's theta matrix and the theta matrix produced by scoring the training data of the latter topic model (back-fitting). To be precise:

1. Build a topic model (CTM only, in this case)
2. Score the training corpus against the fitted topic model (using "average" prevalence method)
3. Compute difference in theta values from topic model and scored result

Most documents have theta values consistent to 1e-06, which is great. OTOH, impacted documents can have their largest difference in theta values up to 60% (e.g., for document X and topic Y, fitted theta value was ~60% but scored theta value was ~0%). **Note:** This is after manually accounting for the two bugs I've reported recently (i.e., don't score documents with 1 term or 1 distinct term, and ensure mu is a matrix in fitNewDocuments for CTMs).

I'm using spectral initialization with x64 MRO and the scored data was produced on the same machine. Corpus size is ~50K documents with ~1K distinct terms. FWIW, I've noticed that back-fitted documents with big theta discrepancies tend to occur when the cleaned document has fewer terms in it. E.g., the problematic document X above has 2 distinct terms, each occurring once.

Please let me know if there's a way to ensure all back-fitted documents have theta values consistent to 1e-06. Thanks, again!

**Comment by bstewart** [comment]
Okay so I am pretty confident I know what the issue here is and I'd be curious on your thoughts about what would work best for your application.

The problem is that the model hasn't truly converged.  The order of updates is:
1) documents
2) global parameters
3) convergence check
4) if not converged, go to 1

This means that when its converged the observed thetas are actually not the ones that go with the global parameters (rather the global parameters are the best fit for the observed thetas).  Which you want really depends on what you are interested in but if the model had completely converged they would be exactly the same.

You are looking at rare words which don't have that big an impact on the overall convergence criterion and thus my still be moving at the moment convergence is declared. However while they won't have a big impact on the whole, they can have an arbitrarily large impact on any given document.

There are a couple of options:
1) Set the convergence tolerance to something ridiculous and run the model a really long time.  This is probably the most proper thing to do but honestly isn't even guaranteed to work every time.  The algorithm is nonconjugate variational inference so its actually possible for the change in the bound to be negative.  This in turn means that we can hit a stopping criterion without the model actually ceasing to move.

2) Simply run the fitNewDocuments() function for everything (training documents and new documents).  This will force the old documents into using the same parameters used to fit the new documents.

Another option would be to change the package to have an option which takes one more pass through the documents after convergence is reached if the user requests it via an option.  This would take a bit of time to put in, but is feasible.

Honestly I'd recommend option 2.  It is conceptually straightforward and addresses your concern.
