### ISSUE TITLE
Feature suggestion: enable to omit plot from plot.estimateEffect()

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#83]
Hi Brandon,

I'm currently working on a shiny app (to be evolved into an R package eventually) for interpreting and visualizing structural topic models.  A very early version is available here:
http://polsoz.uni-bamberg.de/stminsights_ted/
One issue I face is that carrying over the base plots to ggplot is not easy, because apparently shiny apps don't like it if you throw several plots within one function at them. The workflow goes like this:
1. Call estimateEffect and save means, CI's, etc.
2. Construct dataframe
3. Push to ggplot
During the first step the corresponding estimateEffect plot will be shown which shiny immediately displays without going through the next steps. I tried "catching" the plot with an empty file and `dev.off()`, but this doesn't work either.
Could you please consider adding a parameter to the function, e.g. a boolean`omit.plot`, which if it is set to `TRUE` does omit the plot from `estimateEffect()`? This would be super helpful. In case you have another suggestion for this I'd be happy to hear about it.

By the way: I just listened to Justin Grimmer's talk about your joint work on causal effects for highly dimensional data and this seems like yet another groundbreaking work. I'm super excited for the corresponding code! :)

**Comment by methodds** [comment]
Well look what I just found:
https://cran.r-project.org/web/packages/stmgui/stmgui.pdf
=D

**Comment by tingleyd** [comment]
:)

but in the land of STM, all are welcome!!!! I really like what you've
started!!



Dustin Tingley
Government Department
Harvard University
http://scholar.harvard.edu/dtingley

On Wed, Jul 12, 2017 at 6:19 PM, Carsten Schwemmer <notifications@github.com

**Comment by methodds** [comment]
thank you for the kind words! :) Do you know whether Dan is still actively working on the package? It seems like there are [some issues](https://github.com/dzangri/stmGUI/issues/24) when using the latest STM versions.

**Comment by tingleyd** [comment]
I don't think Dan has worked on it for a bit. He's busy changing the world.

Yeah, its just due to the update of STM. Making the changes are pretty
minor. CC'ing Dan now. Dan what do you think? This was a small migration of
some command names we corresponded awhile ago.

Maybe Carsten liason with Dan in the stmGUI github? Carsten you were doing
some great work in your proto-type shiny stm app. Are people interested in
merging streams some? Or, perhaps let the two apps and Carsten yours is
more the stmview wherein you're more dialed in on cases where someone has
already estimated an stm model and can upload it?

just ideas, hopefully yall can chat!



Dustin Tingley
Government Department
Harvard University
http://scholar.harvard.edu/dtingley

On Wed, Jul 12, 2017 at 7:07 PM, Carsten Schwemmer <notifications@github.com

**Comment by methodds** [comment]
Sure, it would be awesome for me to join forces with you. I think both options -  one "big" app or two separated ones -  have pros and cons. But as there is already quite some overlap between the apps, maybe some features can just be ported, for example the option to load already estimated models.

**Comment by bstewart** [comment]
I added an omit.plot option as you suggested/requested.

I totally agree with Dustin- the more the merrier.  A proper GUI for stm strikes me as very challenging and I definitely think there is space for more than one.  If I can help with anything feel free to open another issue.  Sorry this one took so long to deal with!

**Comment by methodds** [comment]
thank you so much for that option, this will be very useful :)
